#!/usr/bin/env python

from Tkinter import *
import socket
import thread
import time

class FOBCONNECT(fobconn):
    
    def __init__(fob1, host, port):
        fob1.host = "10.0.0.15"
        fob1.port = 37450
        fob1.s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        fob1.s.bind((fob1.host, fob1.port))

class MoBo_Window(Frame):

    def bOn(mobo):   
        s.send("bO")
        print ("Basement On")

    def bOff(mobo):
        s.send("bF")
        print ("Basement Off") 

    def lOn(mobo):
        s.send("lO")
        print ("Living room on")  
  
    def lOff(mobo):
        s.send("lF")
        print ("Living room off") 

    def aOn(mobo):
        s.send("aO")
        print ("All On!")

    def aOff(mobo):
        s.send("aF")
        print ("All Off!")

    def q(mobo):
        s.send("qp")
        sys.exit()
        print ("Adios Muchachos")


    def mainWindow(mobo):

        mobo.qp = Button(mobo)
        mobo.qp["text"] = "Quit"
        mobo.qp["fg"] = "red"
        mobo.qp["bg"] = "gray"
        mobo.qp["command"] = mobo.q
        mobo.qp["height"] = 5
        mobo.qp["width"] = 10

        mobo.qp.grid(row=4, columnspan=2)

        mobo.bO = Button(mobo)
        mobo.bO["text"] = "Basement On"
        mobo.bO["fg"] = "green"
        mobo.bO["command"] = mobo.bOn
        mobo.bO["height"] = 5
        mobo.bO["width"] = 10

        mobo.bO.grid(row=0, column=0)

        mobo.bF = Button(mobo)
        mobo.bF["text"] = "Basement Off"
        mobo.bF["fg"] = "red"
        mobo.bF["command"] = mobo.bOff
        mobo.bF["height"] = 5
        mobo.bF["width"] = 10

        mobo.bF.grid(row=1, column=0)

        mobo.lO = Button(mobo) 
        mobo.lO["text"] = "Living Room On"
        mobo.lO["fg"] = "green" 
        mobo.lO ["command"] = mobo.lOn
        mobo.lO["height"] = 5
        mobo.lO["width"] = 10

        mobo.lO.grid(row=0, column=1)

        mobo.lf = Button(mobo)
        mobo.lf["text"] = "Living Room Off"
        mobo.lf["fg"] = "red"
        mobo.lf["command"] = mobo.lOff
        mobo.lf["height"] = 5
        mobo.lf["width"] = 10

        mobo.lf.grid(row=1, column=1)

        mobo.aO = Button(mobo)
        mobo.aO["text"] = "All On"
        mobo.aO["fg"] = "green"
        mobo.aO["bg"] = "black"
        mobo.aO["command"] = mobo.aOn
        mobo.aO["height"] = 5
        mobo.aO["width"] = 10

        mobo.aO.grid(row=2, columnspan=2)

        mobo.aF = Button(mobo)
        mobo.aF["text"] =  "All Off"
        mobo.aF["fg"] = "red"
        mobo.aF["bg"] = "black" 
        mobo.aF["command"] = mobo.aOff
        mobo.aF["height"] = 5
        mobo.aF["width"] = 10

        mobo.aF.grid(row=3, columnspan=2)

    def __init__(mobo, master=None):
        Frame.__init__(mobo, master)
        mobo.pack()
        mobo.mainWindow()

root = Tk()
root.wm_title("Welcome to Motherbase")
app = Application(master=root)
app.mainloop()
root.destroy()
